import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'display-lg': ['Inter'],
                'body-lg': ['Inter'],
                'headline-md': ['Inter'],
                'display-lg-mobile': ['Inter'],
                'body-md': ['Inter'],
                'mono-data': ['Inter'],
                'label-caps': ['Inter'],
            },
            colors: {
                'inverse-surface': '#213145',
                'on-surface': '#0b1c30',
                'on-background': '#0b1c30',
                'on-primary-fixed': '#001d32',
                'on-primary-container': '#f3f7ff',
                'on-primary': '#ffffff',
                'on-secondary-container': '#5c636e',
                'tertiary-fixed': '#e0e3e5',
                'on-secondary': '#ffffff',
                surface: '#f8f9ff',
                'on-primary-fixed-variant': '#004b74',
                'on-surface-variant': '#404850',
                'surface-container-highest': '#d3e4fe',
                'surface-bright': '#f8f9ff',
                'primary-container': '#0077b5',
                'surface-variant': '#d3e4fe',
                'secondary-container': '#dae0ed',
                error: '#ba1a1a',
                'surface-container': '#e5eeff',
                'inverse-on-surface': '#eaf1ff',
                'primary-fixed-dim': '#93ccff',
                'surface-container-lowest': '#ffffff',
                'tertiary-fixed-dim': '#c4c7c9',
                'on-secondary-fixed-variant': '#404752',
                primary: '#005d8f',
                'surface-container-high': '#dce9ff',
                secondary: '#585f6a',
                'on-error-container': '#93000a',
                'on-tertiary-fixed': '#191c1e',
                'surface-tint': '#006398',
                tertiary: '#56595b',
                'surface-dim': '#cbdbf5',
                'tertiary-container': '#6f7274',
                'on-tertiary-container': '#f5f7f9',
                'secondary-fixed-dim': '#c0c7d4',
                'inverse-primary': '#93ccff',
                'primary-fixed': '#cde5ff',
                'outline-variant': '#bfc7d1',
                'surface-container-low': '#eff4ff',
                'on-secondary-fixed': '#151c26',
                'secondary-fixed': '#dce3f0',
                'on-tertiary': '#ffffff',
                outline: '#707881',
                'error-container': '#ffdad6',
                'on-error': '#ffffff',
                background: '#f8f9ff',
                'on-tertiary-fixed-variant': '#444749',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'stack-sm': '8px',
                'stack-lg': '32px',
                'container-max': '1200px',
                unit: '8px',
                'stack-md': '16px',
                'margin-mobile': '16px',
                'margin-desktop': '40px',
                gutter: '24px',
            },
            fontSize: {
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
            },
        },
    },

    plugins: [forms],
};
